name: Debug build

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ViniciusRed/android-public-build@debug
        with:
          token: ${{ secrets.GITHUB_TOKEN }}