name: Build

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ViniciusRed/android-public-build@Master
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            TG_TOKEN: ${{ secrets.TG_TOKEN }}
